=== aprogrammerlostinthisworld/CFGS_1DAW/Lenguaje de Marcas/Examen XML, Schema/Examen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="centro_educativo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estudiante" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="18"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="asignaturas" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="Nombre" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:maxLength value="50"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="calificacion" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="0"/>
                                                <xs:maxInclusive value="10"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aprogrammerlostinthisworld/CFGS_1DAW/Lenguaje de Marcas/Examen XML, Schema/Examen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<centro_educativo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Examen.xsd">
    
    <estudiante codigo="1">
        <nombre>Eufrasio Pérez López</nombre>
        <edad>18</edad>
        <asignaturas Nombre="Lenguajes de Marcas" calificacion="3"/>
        <asignaturas Nombre="Formación y Orientación Laboral" calificacion="9"/>
        <asignaturas Nombre="Programación" calificacion="4"/>
        <asignaturas Nombre="Bases de Datos" calificacion="7"/>
        <asignaturas Nombre="Sistemas Informáticos" calificacion="5"/>
        <asignaturas Nombre="Entornos de Desarrollo" calificacion="6"/>
    </estudiante>
    
    <estudiante codigo="2">
        <nombre>Romualdo Jiménez Sahagún</nombre>
        <edad>23</edad>
        <asignaturas Nombre="Lenguajes de Marcas" calificacion="4"/>
        <asignaturas Nombre="Formación y Orientación Laboral" calificacion="10"/>
        <asignaturas Nombre="Programación" calificacion="3"/>
        <asignaturas Nombre="Bases de Datos" calificacion="5"/>
        <asignaturas Nombre="Sistemas Informáticos" calificacion="5"/>
        <asignaturas Nombre="Entornos de Desarrollo" calificacion="6"/>
    </estudiante>
    
</centro_educativo>
